version: '3'

services: 

    app: 
        build:  .
        container_name: app
        volumes:
            - .:/var/www

    nginx:
        build: /home/emerpapp/Projects/DevOps/laravel/.docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "8000:80"
        volumes: 
            - .:/var/www
    redis:
        image: redis:alpine
        expose:
            - 6379